DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE (ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHOR(ID),
    GENRE_ID BIGINT  REFERENCES GENRE(ID)
);
